var heros = [
  {
    id: 105,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/105/105.jpg",
    name: "廉颇",
    types: [3],
    isFree: false,
    isNew: false,
    nickname: "lianpo",
  },
  {
    id: 106,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/106/106.jpg",
    name: "小乔",
    types: [2],
    isFree: false,
    isNew: false,
    nickname: "恋之微风",
  },
  {
    id: 107,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/107/107.jpg",
    name: "赵云",
    types: [1, 4],
    isFree: false,
    isNew: false,
    nickname: "苍天翔龙",
  },
  {
    id: 108,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/108/108.jpg",
    name: "墨子",
    types: [2, 1],
    isFree: false,
    isNew: false,
    nickname: "和平守望",
  },
  {
    id: 109,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/109/109.jpg",
    name: "妲己",
    types: [2],
    isFree: false,
    isNew: true,
    nickname: "魅力之狐",
  },
  {
    id: 110,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/110/110.jpg",
    name: "嬴政",
    types: [2],
    isFree: false,
    isNew: false,
    nickname: "王者独尊",
  },
  {
    id: 111,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/111/111.jpg",
    name: "孙尚香",
    types: [5],
    isFree: false,
    isNew: false,
    nickname: "千金重弩",
  },
  {
    id: 112,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/112/112.jpg",
    name: "鲁班七号",
    types: [5],
    isFree: false,
    isNew: false,
    nickname: "机关造物",
  },
  {
    id: 113,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/113/113.jpg",
    name: "庄周",
    types: [6, 3],
    isFree: false,
    isNew: false,
    nickname: "逍遥梦幻",
  },
  {
    id: 114,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/114/114.jpg",
    name: "刘禅",
    types: [6, 3],
    isFree: false,
    isNew: false,
    nickname: "暴走机关",
  },
  {
    id: 115,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/115/115.jpg",
    name: "高渐离",
    types: [2],
    isFree: false,
    isNew: false,
    nickname: "叛逆吟游",
  },
  {
    id: 116,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/116/116.jpg",
    name: "阿轲",
    types: [4],
    isFree: false,
    isNew: false,
    nickname: "信念之刃",
  },
  {
    id: 117,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/117/117.jpg",
    name: "钟无艳",
    types: [1, 3],
    isFree: false,
    isNew: false,
    nickname: "野蛮之锤",
  },
  {
    id: 118,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/118/118.jpg",
    name: "孙膑",
    types: [6, 2],
    isFree: false,
    isNew: false,
    nickname: "逆流之时",
  },
  {
    id: 119,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/119/119.jpg",
    name: "扁鹊",
    types: [2],
    isFree: false,
    isNew: false,
    nickname: "善恶怪医",
  },
  {
    id: 120,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/120/120.jpg",
    name: "白起",
    types: [3],
    isFree: false,
    isNew: false,
    nickname: "最终兵器",
  },
  {
    id: 121,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/121/121.jpg",
    name: "芈月",
    types: [2, 3],
    isFree: false,
    isNew: false,
    nickname: "永恒之月",
  },
  {
    id: 123,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/123/123.jpg",
    name: "吕布",
    types: [1, 3],
    isFree: false,
    isNew: false,
    nickname: "无双之魔",
  },
  {
    id: 124,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/124/124.jpg",
    name: "周瑜",
    types: [2],
    isFree: false,
    isNew: false,
    nickname: "铁血都督",
  },
  {
    id: 126,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/126/126.jpg",
    name: "夏侯惇",
    types: [3, 1],
    isFree: false,
    isNew: false,
    nickname: "不羁之风",
  },
  {
    id: 127,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/127/127.jpg",
    name: "甄姬",
    types: [2],
    isFree: false,
    isNew: false,
    nickname: "洛神降临",
  },
  {
    id: 128,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/128/128.jpg",
    name: "曹操",
    types: [1],
    isFree: false,
    isNew: false,
    nickname: "鲜血枭雄",
  },
  {
    id: 129,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/129/129.jpg",
    name: "典韦",
    types: [1],
    isFree: true,
    isNew: false,
    nickname: "狂战士",
    bigImg : "https://game.gtimg.cn/images/yxzj/img201606/heroimg/129/129-freehover.png"
  },
  {
    id: 130,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/130/130.jpg",
    name: "宫本武藏",
    types: [1],
    isFree: false,
    isNew: false,
    nickname: "剑圣",
  },
  {
    id: 131,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/131/131.jpg",
    name: "李白",
    types: [4],
    isFree: false,
    isNew: false,
    nickname: "青莲剑仙",
  },
  {
    id: 132,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/132/132.jpg",
    name: "马可波罗",
    types: [5],
    isFree: false,
    isNew: false,
    nickname: "远游之枪",
  },
  {
    id: 133,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/133/133.jpg",
    name: "狄仁杰",
    types: [5],
    isFree: false,
    isNew: true,
    nickname: "断案大师",
  },
  {
    id: 134,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/134/134.jpg",
    name: "达摩",
    types: [1, 3],
    isFree: false,
    isNew: false,
    nickname: "拳僧",
  },
  {
    id: 135,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/135/135.jpg",
    name: "项羽",
    types: [3],
    isFree: false,
    isNew: false,
    nickname: "霸王",
  },
  {
    id: 136,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/136/136.jpg",
    name: "武则天",
    types: [2],
    isFree: false,
    isNew: false,
    nickname: "女帝",
  },
  {
    id: 139,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/139/139.jpg",
    name: "老夫子",
    types: [1],
    isFree: false,
    isNew: false,
    nickname: "万古长明",
  },
  {
    id: 140,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/140/140.jpg",
    name: "关羽",
    types: [1],
    isFree: false,
    isNew: false,
    nickname: "一骑当千",
  },
  {
    id: 141,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/141/141.jpg",
    name: "貂蝉",
    types: [2, 4],
    isFree: false,
    isNew: false,
    nickname: "绝世舞姬",
  },
  {
    id: 142,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/142/142.jpg",
    name: "安琪拉",
    types: [2],
    isFree: false,
    isNew: false,
    nickname: "暗夜萝莉",
  },
  {
    id: 144,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/144/144.jpg",
    name: "程咬金",
    types: [3, 1],
    isFree: false,
    isNew: false,
    nickname: "热烈之斧",
  },
  {
    id: 146,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/146/146.jpg",
    name: "露娜",
    types: [1, 2],
    isFree: false,
    isNew: false,
    nickname: "月光之女",
  },
  {
    id: 148,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/148/148.jpg",
    name: "姜子牙",
    types: [2, 6],
    isFree: false,
    isNew: false,
    nickname: "太古魔导",
  },
  {
    id: 149,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/149/149.jpg",
    name: "刘邦",
    types: [3],
    isFree: false,
    isNew: false,
    nickname: "双面君主",
  },
  {
    id: 150,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/150/150.jpg",
    name: "韩信",
    types: [4],
    isFree: false,
    isNew: false,
    nickname: "国士无双",
  },
  {
    id: 152,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/152/152.jpg",
    name: "王昭君",
    types: [2],
    isFree: true,
    isNew: false,
    nickname: "冰雪之华",
    bigImg: "https://game.gtimg.cn/images/yxzj/img201606/heroimg/152/152-freehover.png"
  },
  {
    id: 153,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/153/153.jpg",
    name: "兰陵王",
    types: [4],
    isFree: false,
    isNew: false,
    nickname: "暗影刀锋",
  },
  {
    id: 154,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/154/154.jpg",
    name: "花木兰",
    types: [1, 4],
    isFree: false,
    isNew: false,
    nickname: "传说之刃",
  },
  {
    id: 156,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/156/156.jpg",
    name: "张良",
    types: [2],
    isFree: false,
    isNew: false,
    nickname: "言灵之书",
  },
  {
    id: 157,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/157/157.jpg",
    name: "不知火舞",
    types: [2, 4],
    isFree: false,
    isNew: false,
    nickname: "明媚烈焰",
  },
  {
    id: 162,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/162/162.jpg",
    name: "娜可露露",
    types: [4],
    isFree: false,
    isNew: false,
    nickname: "鹰之守护",
  },
  {
    id: 163,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/163/163.jpg",
    name: "橘右京",
    types: [4, 1],
    isFree: false,
    isNew: false,
    nickname: "神梦一刀",
  },
  {
    id: 166,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/166/166.jpg",
    name: "亚瑟",
    types: [1, 3],
    isFree: false,
    isNew: true,
    nickname: "圣骑之力",
  },
  {
    id: 167,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/167/167.jpg",
    name: "孙悟空",
    types: [4, 1],
    isFree: false,
    isNew: false,
    nickname: "齐天大圣",
  },
  {
    id: 168,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/168/168.jpg",
    name: "牛魔",
    types: [3, 6],
    isFree: false,
    isNew: false,
    nickname: "精英酋长",
  },
  {
    id: 169,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/169/169.jpg",
    name: "后羿",
    types: [5],
    isFree: false,
    isNew: false,
    nickname: "半神之弓",
  },
  {
    id: 170,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/170/170.jpg",
    name: "刘备",
    types: [1],
    isFree: false,
    isNew: false,
    nickname: "仁德义枪",
  },
  {
    id: 171,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/171/171.jpg",
    name: "张飞",
    types: [3, 6],
    isFree: false,
    isNew: false,
    nickname: "禁血狂兽",
  },
  {
    id: 173,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/173/173.jpg",
    name: "李元芳",
    types: [5],
    isFree: false,
    isNew: false,
    nickname: "王都密探",
  },
  {
    id: 174,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/174/174.jpg",
    name: "虞姬",
    types: [5],
    isFree: false,
    isNew: false,
    nickname: "森之风灵",
  },
  {
    id: 175,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/175/175.jpg",
    name: "钟馗",
    types: [2, 1],
    isFree: false,
    isNew: false,
    nickname: "虚灵城判",
  },
  {
    id: 177,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/177/177.jpg",
    name: "成吉思汗",
    types: [5],
    isFree: false,
    isNew: false,
    nickname: "苍狼末裔",
  },
  {
    id: 178,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/178/178.jpg",
    name: "杨戬",
    types: [1],
    isFree: false,
    isNew: false,
    nickname: "根源之目",
  },
  {
    id: 183,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/183/183.jpg",
    name: "雅典娜",
    types: [1],
    isFree: false,
    isNew: false,
    nickname: "圣域余晖",
  },
  {
    id: 184,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/184/184.jpg",
    name: "蔡文姬",
    types: [6],
    isFree: false,
    isNew: false,
    nickname: "天籁弦音",
  },
  {
    id: 186,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/186/186.jpg",
    name: "太乙真人",
    types: [6, 3],
    isFree: false,
    isNew: false,
    nickname: "炼金大师",
  },
  {
    id: 180,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/180/180.jpg",
    name: "哪吒",
    types: [1],
    isFree: false,
    isNew: false,
    nickname: "桀骜炎枪",
  },
  {
    id: 190,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/190/190.jpg",
    name: "诸葛亮",
    types: [2],
    isFree: false,
    isNew: false,
    nickname: "绝代智谋",
  },
  {
    id: 192,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/192/192.jpg",
    name: "黄忠",
    types: [5],
    isFree: false,
    isNew: false,
    nickname: "燃魂重炮",
  },
  {
    id: 191,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/191/191.jpg",
    name: "大乔",
    types: [6],
    isFree: false,
    isNew: false,
    nickname: "沧海之曜",
  },
  {
    id: 187,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/187/187.jpg",
    name: "东皇太一",
    types: [3],
    isFree: true,
    isNew: false,
    nickname: "噬灭日蚀",
    bigImg : "https://game.gtimg.cn/images/yxzj/img201606/heroimg/187/187-freehover.png"
  },
  {
    id: 182,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/182/182.jpg",
    name: "干将莫邪",
    types: [2],
    isFree: false,
    isNew: false,
    nickname: "淬命双剑",
  },
  {
    id: 189,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/189/189.jpg",
    name: "鬼谷子",
    types: [6],
    isFree: false,
    isNew: false,
    nickname: "万物有灵",
  },
  {
    id: 193,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/193/193.jpg",
    name: "铠",
    types: [1, 3],
    isFree: false,
    isNew: false,
    nickname: "破灭刃锋",
  },
  {
    id: 196,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/196/196.jpg",
    name: "百里守约",
    types: [5, 4],
    isFree: false,
    isNew: false,
    nickname: "静谧之眼",
  },
  {
    id: 195,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/195/195.jpg",
    name: "百里玄策",
    types: [4],
    isFree: true,
    isNew: false,
    nickname: "嚣狂之镰",
    bigImg : "https://game.gtimg.cn/images/yxzj/img201606/heroimg/195/195-freehover.png"
  },
  {
    id: 194,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/194/194.jpg",
    name: "苏烈",
    types: [3, 1],
    isFree: false,
    isNew: false,
    nickname: "不屈铁壁",
  },
  {
    id: 198,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/198/198.jpg",
    name: "梦奇",
    types: [3],
    isFree: false,
    isNew: false,
    nickname: "入梦之灵",
  },
  {
    id: 179,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/179/179.jpg",
    name: "女娲",
    types: [2],
    isFree: false,
    isNew: false,
    nickname: "至高创世",
  },
  {
    id: 501,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/501/501.jpg",
    name: "明世隐",
    types: [6],
    isFree: false,
    isNew: false,
    nickname: "灵魂劫卜",
  },
  {
    id: 199,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/199/199.jpg",
    name: "公孙离",
    types: [5],
    isFree: false,
    isNew: false,
    nickname: "幻舞玲珑",
  },
  {
    id: 176,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/176/176.jpg",
    name: "杨玉环",
    types: [2, 6],
    isFree: false,
    isNew: false,
    nickname: "霓裳风华",
  },
  {
    id: 502,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/502/502.jpg",
    name: "裴擒虎",
    types: [4, 1],
    isFree: false,
    isNew: false,
    nickname: "六合虎拳",
  },
  {
    id: 197,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/197/197.jpg",
    name: "弈星",
    types: [2],
    isFree: false,
    isNew: false,
    nickname: "天元之弈",
  },
  {
    id: 503,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/503/503.jpg",
    name: "狂铁",
    types: [1],
    isFree: false,
    isNew: false,
    nickname: "战车意志",
  },
  {
    id: 504,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/504/504.jpg",
    name: "米莱狄",
    types: [2],
    isFree: false,
    isNew: false,
    nickname: "筑城者",
  },
  {
    id: 125,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/125/125.jpg",
    name: "元歌",
    types: [4],
    isFree: false,
    isNew: false,
    nickname: "无间傀儡",
  },
  {
    id: 510,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/510/510.jpg",
    name: "孙策",
    types: [3, 1],
    isFree: false,
    isNew: false,
    nickname: "光明之海",
  },
  {
    id: 137,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/137/137.jpg",
    name: "司马懿",
    types: [4, 2],
    isFree: false,
    isNew: false,
    nickname: "寂灭之心",
  },
  {
    id: 509,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/509/509.jpg",
    name: "盾山",
    types: [6],
    isFree: false,
    isNew: false,
    nickname: "无尽之盾",
  },
  {
    id: 508,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/508/508.jpg",
    name: "伽罗",
    types: [5],
    isFree: true,
    isNew: false,
    nickname: "破魔之箭",
    bigImg : "https://game.gtimg.cn/images/yxzj/img201606/heroimg/508/508-freehover.png"
  },
  {
    id: 312,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/312/312.jpg",
    name: "沈梦溪",
    types: [2],
    isFree: true,
    isNew: false,
    nickname: "爆弹怪猫",
    bigImg : "https://game.gtimg.cn/images/yxzj/img201606/heroimg/312/312-freehover.png"
  },
  {
    id: 507,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/507/507.jpg",
    name: "李信",
    types: [1],
    isFree: false,
    isNew: false,
    nickname: "谋世之战",
  },
  {
    id: 513,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/513/513.jpg",
    name: "上官婉儿",
    types: [2, 4],
    isFree: false,
    isNew: false,
    nickname: "惊鸿之笔",
  },
  {
    id: 515,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/515/515.jpg",
    name: "嫦娥",
    types: [2, 3],
    isFree: false,
    isNew: false,
    nickname: "寒月公主",
  },
  {
    id: 511,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/511/511.jpg",
    name: "猪八戒",
    types: [3],
    isFree: false,
    isNew: false,
    nickname: "无忧猛士",
  },
  {
    id: 529,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/529/529.jpg",
    name: "盘古",
    types: [1],
    isFree: false,
    isNew: false,
    nickname: "破晓之神",
  },
  {
    id: 505,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/505/505.jpg",
    name: "瑶",
    types: [6],
    isFree: true,
    isNew: false,
    nickname: "鹿灵守心",
    bigImg : "https://game.gtimg.cn/images/yxzj/img201606/heroimg/505/505-freehover.png"
  },
  {
    id: 506,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/506/506.jpg",
    name: "云中君",
    types: [4, 1],
    isFree: false,
    isNew: false,
    nickname: "流云之翼",
  },
  {
    id: 522,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/522/522.jpg",
    name: "曜",
    types: [1],
    isFree: false,
    isNew: false,
    nickname: "星辰之子",
  },
  {
    id: 518,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/518/518.jpg",
    name: "马超",
    types: [1, 4],
    isFree: false,
    isNew: false,
    nickname: "冷晖之枪",
  },
  {
    id: 523,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/523/523.jpg",
    name: "西施",
    types: [2],
    isFree: false,
    isNew: false,
    nickname: "幻纱之灵",
  },
  {
    id: 525,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/525/525.jpg",
    name: "鲁班大师",
    types: [6],
    isFree: false,
    isNew: false,
    nickname: "神匠",
  },
  {
    id: 524,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/524/524.jpg",
    name: "蒙犽",
    types: [5],
    isFree: false,
    isNew: false,
    nickname: "烈炮小子",
  },
  {
    id: 531,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/531/531.jpg",
    name: "镜",
    types: [4],
    isFree: false,
    isNew: false,
    nickname: "破镜之刃",
  },
  {
    id: 527,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/527/527.jpg",
    name: "蒙恬",
    types: [1],
    isFree: false,
    isNew: false,
    nickname: "秩序统将",
  },
  {
    id: 533,
    imgUrl: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/533/533.jpg",
    name: "阿古朵",
    types: [3],
    isFree: false,
    isNew: false,
    nickname: "山林之子",
  },
];

var heroTypes = [
  { id: 3, name: "坦克" },
  { id: 1, name: "战士" },
  { id: 4, name: "刺客" },
  { id: 2, name: "法师" },
  { id: 5, name: "射手" },
  { id: 6, name: "辅助" },
];
